from selenium.webdriver.common.by import By


class OrderPageLocators:
    ZAKAZ_UP = [By.XPATH, "//div[@class='Header_Nav__AGCXC']/button[text()='Заказать']"]
    ZAKAZ__DOWN = [By.XPATH, "//div[@class='Home_RoadMap__2tal_']//button[text()='Заказать']"]
    NAME = [By.XPATH, "//input[@placeholder='* Имя']"]
    SURNAME = [By.XPATH, "//input[@placeholder='* Фамилия']"]
    ADRESS = [By.XPATH, "//input[@placeholder='* Адрес: куда привезти заказ']"]
    METRO_LIST = [By.XPATH, "//input[@placeholder='* Станция метро']"]
    METRO_STATION = [By.XPATH, "//li[5]/button"]
    PHONE = [By.XPATH, "//input[@placeholder='* Телефон: на него позвонит курьер']"]
    BUTTON_NEXT = [By.XPATH, "//button[@class='Button_Button__ra12g Button_Middle__1CSJM' and text()='Далее']"]
    TITLE_ARENDA = [By.CLASS_NAME, "Order_Header__BZXOb"]
    OPEN_KALENDAR = [By.XPATH, "//input[@placeholder='* Когда привезти самокат']"]
    DATE = [By.XPATH, "//div[contains (@class, 'react-datepicker__day--today')]"]
    OPEN_PERIOD_ARENDA = [By.CLASS_NAME, "Dropdown-placeholder"]
    TWO_DAYS = [By.XPATH, "//div[text()='двое суток']"]
    COLOR = [By.ID, "black"]
    COMMENT = [By.XPATH, "//input[@placeholder='Комментарий для курьера']"]
    MODAL_AGREE = [By.CLASS_NAME, "Order_Modal__YZ-d3"]
    TITLE_SUCSSES = [By.XPATH, "//div[@class='Order_ModalHeader__3FDaJ' and text()='Заказ оформлен']"]
    BUTTON_ZAKAZ = [By.XPATH, "//button[@class='Button_Button__ra12g Button_Middle__1CSJM' and text()='Заказать']"]
    BUTTON_YES = [By.XPATH, "//button[@class='Button_Button__ra12g Button_Middle__1CSJM' and text()='Да']"]
    # BUTTON_STATUS = [By.XPATH, "//button[text()='Посмотреть статус']"]
    LOGO_SAMOKAT = [By.CLASS_NAME, "Header_LogoScooter__3lsAR"]
    LOGO_YANDEX = [By.CLASS_NAME, "Header_LogoYandex__3TSOI"]
    TITLE_SAMOKAT = [By.CLASS_NAME, "Home_Header__iJKdX"]
    TITLE_DZEN = [By.XPATH, "//*[@id='dzen-header']"]
